// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

#define TRIANGLE_T uint64_t
#define FACTOR_T uint64_t
#include <inttypes.h>
#include "../triangleNumbers.h"
#include "../factors.h"

int main (int argc, char *argv[]) {
	unsigned long limit;
	if (argc > 1) {
		sscanf(argv[1], "%lu", &limit);
	} else {
		scanf("%lu", &limit);
	}
	fflush(stdout);

	setTriangleNumbers(NULL, 0, 0);

	for (;;) {
		TN_nextTriNum();
		factorize(triNumWrap.seed);
		if (Factor.size >= limit) {
			printf("Your triangle number is %"PRIu64" and your factors are: ", triNumWrap.seed);
			for (int i = 0; i < Factor.size; i++) {
				printf("%"PRIu64" ", Factor.factors[i]);
			}
			printf("\n");
			break;
		}

		#ifdef DEBUG
		printf("Triangle number: %"PRIu64"\n", triNumWrap.seed);
		printf("Factors: ");
		for (int i = 0; i < Factor.size; i++) {
			printf("%"PRIu64" ", Factor.factors[i]);
		}
		printf("\n\n");
		#endif
	}

	freeTriangleNumbers();
	free(Factor.factors);
}
