// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.  4613732

// TODO:  Run performance tests to see whether skip two iterations method or mod 2 method is faster.

var total = 0;
var limit = parseInt(prompt("What the limit for adding up even Fibonacci numbers?"));

var fibonacci = [1, 2];

for (var even = 1; total <= limit; even++)
{
	if (even > 0)
	{
		even = -2; // Going to be incremented later
		total += fibonacci[1];
	}
	fibonacci = [fibonacci[1], fibonacci[0] + fibonacci[1]];
}

alert(total);